#define LB_MACHINE_LISTEN_PORT 8080
#define LB_CLIENT_LISTEN_PORT 9000

#define NUM_PROCS_GEN 1

#define BUF_SZ 1024

// for dispatcher
#define THRESHOLD_PUSH_SLA 10
#define THRESHOLD_PUSH_TIME_PASSED_TO_SLA_RATIO 0.3
#define HOLDQ_CHECK_SLEEP_TIME_MILLISEC 5

